//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blog.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class comments
    {
        public decimal comment_id { get; set; }
        public string comment_author { get; set; }
        public string comment_email { get; set; }
        public string comment_text { get; set; }
        public Nullable<System.DateTime> comment_timestamp { get; set; }
        public Nullable<decimal> comment_post_id { get; set; }
    
        public virtual posts posts { get; set; }
    }
}
