//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blog.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class posts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public posts()
        {
            this.comments = new HashSet<comments>();
        }
    
        public decimal post_id { get; set; }
        public string post_title { get; set; }
        public string post_text { get; set; }
        public string post_author { get; set; }
        public Nullable<System.DateTime> post_change { get; set; }
        public Nullable<System.DateTime> post_approval { get; set; }
        public Nullable<decimal> post_status_published { get; set; }
        public string post_approval_name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<comments> comments { get; set; }
    }
}
